apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  annotations:
    # Existing notification annotations
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "k8s-deployment-status"
    notifications.argoproj.io/subscribe.on-update-started.slack: "k8s-deployment-status"
    notifications.argoproj.io/subscribe.on-update-failed.slack: "k8s-deployment-status"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
